# Generated by Django 5.2.1 on 2025-05-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
